version: '3.8'

services:
  web:
    build: ./
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    ports:
      - 5001:5000
    env_file:
      - .env
    volumes:
      - .:/app
  nginx:
    build: ./nginx
    ports:
    - 1337:80
    depends_on:
    - web